stages:
  - build
  - push

variables:
  IMAGE_NAME: "$DOCKERHUB_USERNAME/frontend"  # replace your-repo-name per service

# Build Docker image
build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:latest .
  only:
    - main

# Push Docker image to Docker Hub
push-image:
  stage: push
  image: docker:20.10.16
  services:
    - docker:dind
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:latest
  only:
    - main
