stages:
  - build
  - push

variables:
  DOCKER_IMAGE: "registry.gitlab.com/sitisalwa/self-nextjs-project"

before_script:
  # Authenticate with GitLab Container Registry
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

build-job:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest

push-job:
  stage: push
  script:
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest
